---
- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: master
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: master
  name: repo

- src: https://github.com/open-io/ansible-role-openio-meta0.git
  version: master
  name: meta0

- src: https://github.com/open-io/ansible-role-openio-conscience.git
  version: master
  name: conscience

- src: https://github.com/open-io/ansible-role-openio-oioproxy.git
  version: master
  name: oioproxy
...
